val MatchData = sc.textFile("/project/MatchNew")
val SplitData = MatchData.map(line => line.split(","))
val SampleData = SplitData.map( x => (x(5),(x(11))) )
val ReduceData = SampleData.map( x=> (x,1) ).reduceByKey(_+_)
ReduceData.collect()
val SwapData = ReduceData.map( item => item.swap )
val SortData = SwapData.sortByKey(ascending = false)
val ForeachData = SortData.collect.foreach(println)